on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7', '3.10', '3.13.0-beta.2']
    name: Python ${{ matrix.python-version }} Linux tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -Werr tests.py

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.12']
    name: Python ${{ matrix.python-version }} Windows tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -Werr tests.py

  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.11']
    name: Python ${{ matrix.python-version }} Macos tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -Werr tests.py
